### ISSUE TITLE
请问如何用快捷指令获取回复呢？

### ISSUE THREAD

**Issue by MartinZiYun** [XiaoXinYo/Bing-Chat#10]
如何用快捷指令调用API；格式是什么呢？感谢开发大大！

**Comment by ykaiqx** [comment]
请求地址：https://127.0.0.1:5000/api
方式：GET/POST
参数：question

**Comment by ykaiqx** [comment]
参考
![1021677931218_ pic](https://user-images.githubusercontent.com/56395004/222899899-73ff31c1-90df-46dd-af89-88d12a72086a.jpg)
![1031677931223_ pic](https://user-images.githubusercontent.com/56395004/222899903-378ed195-f9b6-4d35-aab4-ebc0bdb80a8a.jpg)

**Comment by MartinZiYun** [comment]
感谢感谢！！！
