### ISSUE TITLE
代码类回复无法显示

### ISSUE THREAD

**Issue by systemoutprintlnhelloworld** [XiaoXinYo/Bing-Chat#14]
错误截图：https://imgse.com/i/ppmBxx0
仅回复[object Object]
已复现三次

**Comment by systemoutprintlnhelloworld** [comment]
只有web2.html出现该异常

**Comment by systemoutprintlnhelloworld** [comment]
> 错误截图：https://imgse.com/i/ppmBxx0 仅回复[object Object] 已复现三次

只有web2.html出现该异常

**Comment by ykaiqx** [comment]
这个示例并不是我写的，你可以联系 @Hzzy2O

**Comment by systemoutprintlnhelloworld** [comment]
> 这个示例并不是我写的，你可以联系 @Hzzy2O

他的网页好像修改了些https://imgse.com/i/ppmyPZ8，大大可以尝试着更新下？

**Comment by systemoutprintlnhelloworld** [comment]
> 这个示例并不是我写的，你可以联系 @Hzzy2O

他写的网页好像更新了，有些改动https://imgse.com/i/ppmyPZ8
大大可以尝试着更新下？我这边用你的程序不能在他网页上运行

**Comment by ykaiqx** [comment]
没更新，最后更新时间是六天前

**Comment by duoduohe** [comment]
我下午更新
