### ISSUE TITLE
我有个想法

### ISSUE THREAD

**Issue by duoduohe** [XiaoXinYo/Bing-Chat#15]
就是能不能接入chatgpt，然后可以动态切换对话模型，这有一个集合了搜索能力的chatgpt: https://github.com/circlestarzero/EX-chatGPT
或者普通的chatgpt也可以

**Comment by ykaiqx** [comment]
此仓库，主要是作为bing的。你可以联系我（xiaoxinyoo@qq.com），单独讨论。
