### ISSUE TITLE
通过GET请求方式，不能连续对话

### ISSUE THREAD

**Issue by skyingbird** [XiaoXinYo/Bing-Chat#18]
如题，请问如何用GET或POST方式实现连续对话？感谢！

**Comment by Coaixy** [comment]
暂时未实现

发自我的 iPhone

在 2023年3月12日，14:40，skyingbird ***@***.***> 写道：

﻿

如题，请问如何用GET或POST方式实现连续对话？感谢！

**Comment by ykaiqx** [comment]
我是这样想的：每次都将前一个的问题和回答都附上。

**Comment by skyingbird** [comment]
是的，按照chatGPT的接口，把前面的问题和答案都附上就可以连续对话了，但用GET/POST要怎么加呢？
另外，您的示例用WebSocket是可以连续对话的，说明服务端是支持连续对话的，期待您增加GET/POST的连续对话接口。感谢！

> 我是这样想的：每次都将前一个的问题和回答都附上。

**Comment by ykaiqx** [comment]
> 是的，按照chatGPT的接口，把前面的问题和答案都附上就可以连续对话了，但用GET/POST要怎么加呢？ 另外，您的示例用WebSocket是可以连续对话的，说明服务端是支持连续对话的，期待您增加GET/POST的连续对话接口。感谢！
> 
> > 我是这样想的：每次都将前一个的问题和回答都附上。

将其作为question参数的值。我正在改进API的接口，预计今晚就可以更新。

**Comment by skyingbird** [comment]
您的意思是这样吗？
http://127.0.0.1:5000/api?style=balanced&question=我问你：北京天气怎样？你回答：多云转阴。我现在问你：上海呢？
我试了，确实可以连续对话，哈哈，真是个简单粗暴的方法。谢谢，如果您有更好的办法，请赐教。

**Comment by ykaiqx** [comment]
> 您的意思是这样吗？ [http://127.0.0.1:5000/api?style=balanced&question=我问你：北京天气怎样？你回答：多云转阴。我现在问你：上海呢？](http://127.0.0.1:5000/api?style=balanced&question=%E6%88%91%E9%97%AE%E4%BD%A0%EF%BC%9A%E5%8C%97%E4%BA%AC%E5%A4%A9%E6%B0%94%E6%80%8E%E6%A0%B7%EF%BC%9F%E4%BD%A0%E5%9B%9E%E7%AD%94%EF%BC%9A%E5%A4%9A%E4%BA%91%E8%BD%AC%E9%98%B4%E3%80%82%E6%88%91%E7%8E%B0%E5%9C%A8%E9%97%AE%E4%BD%A0%EF%BC%9A%E4%B8%8A%E6%B5%B7%E5%91%A2%EF%BC%9F) 我试了，确实可以连续对话，哈哈，真是个简单粗暴的方法。谢谢，如果您有更好的办法，请赐教。

是这个意思。
我准备对API接口进行以下的改进：
1. 当请求时token参数没有被填写，那么就被认为是一个新的对话，将会返回token（下次请求带上）。
2. 带上token值后，则会延续上一个对话。

**Comment by skyingbird** [comment]
太好了，感谢！不知Bing有没有像chatgpt那样的system的角色设定词，如果有的话，建议加上可更改的接口

**Comment by skyingbird** [comment]
另外，不知服务端是否解除了连续对话最多10次的限制？如果没有解除，建议在返回值里增加一个参数“当前是连续对话中的第几次”的参数

**Comment by ykaiqx** [comment]
> 太好了，感谢！不知Bing有没有像chatgpt那样的system的角色设定词，如果有的话，建议加上可更改的接口

目前没有。

**Comment by ykaiqx** [comment]
> 另外，不知服务端是否解除了连续对话最多10次的限制？如果没有解除，建议在返回值里增加一个参数“当前是连续对话中的第几次”的参数

更新后，API会和WebsSocket一样将会有一个reset参数，如果为true，下次对话将被重置。

**Comment by ykaiqx** [comment]
已更新

**Comment by skyingbird** [comment]
感谢！测试好用！
不过小弟遇到一个问题，如果在局域网的另一台机访问服务端（形如http://192.168.2.29:5004/api?xxxx），提示“由于目标计算机积极拒绝，无法连接”，我已经关掉了两台机的防火墙，仍热报错，不知是何原因，特来讨教。

**Comment by ykaiqx** [comment]
检查第15、16行的 监听地址和端口是否正确。这个报错是py端给的吧

**Comment by skyingbird** [comment]
是的，解决了，谢谢
