### ISSUE TITLE
ws连接很慢

### ISSUE THREAD

**Issue by Do1e** [XiaoXinYo/Bing-Chat#19]
example中的web和web3都是ws_steam，打开之后后台马上就显示了连接。但是web2用的是ws，打开之后会加载好久，后台也没有显示连接，这是为什么呢？

**Comment by ykaiqx** [comment]
关于整体传输（ws）和流传输（ws_steam），整体传输由于要等待Bing完全响应才能开始传输，所以时间要久一点。流传输会一部分的返回，所以看起来比较快，但其实最终的完成时间都是一样的.

**Comment by Do1e** [comment]
你可能误解了。我是指刚打开网页的时候，web2有一个正方形要旋转很久才进去，这是什么原因引起的呢？

**Comment by ykaiqx** [comment]
引用了资源（css，js）。unpkg有时候会比较慢，你可以替换为其他的cdn

**Comment by Do1e** [comment]
好的，多谢了
