### ISSUE TITLE
EdgeGPT库已更新到最新版本(0.0.56.2)，但仍报错。

### ISSUE THREAD

**Issue by skyingbird** [XiaoXinYo/Bing-Chat#20]
Successfully installed EdgeGPT-0.0.56.2 httpcore-0.16.3 httpx-0.23.3 rfc3986-1.5.0
API访问报错：
http://127.0.0.1:5000/api?token=&style=balanced&question=北京天气怎么样
{"code": 500, "message": "未知错误"}

**Comment by ykaiqx** [comment]
我刚才试了几次，并没有出现你的问题。是一直显示 未知错误 还是 有时候？

**Comment by skyingbird** [comment]
今天下午开始一直都这样

**Comment by skyingbird** [comment]
是我程序的问题，不好意思
