### ISSUE TITLE
web2显示bug

### ISSUE THREAD

**Issue by Do1e** [XiaoXinYo/Bing-Chat#22]
![$M{S(UHX`YT$WDS7{U4NB3R](https://user-images.githubusercontent.com/73533898/226329961-d61741b1-bf9e-46e3-898f-f6942cb5c6b4.png)

如图中的这个其实后台实际输出的内容如下：

\`torch.nn.Parameter()\`函数可以将一个不可训练的tensor转换成可以训练的类型parameter，并将这个parameter绑定到这个module里面。在定义网络时这个tensor就是一个可以训练的参数了。使用这个函数的目的也是想让某些变量在学习的过程中不断的修改其值以达到最优化。 

\`torch.parallel\`是PyTorch中的一个并行计算库，可以实现多GPU的并行计算。在使用\`torch.parallel\`之后，网络中的parameter变成了Tensor，是因为\`torch.parallel\`会将网络中的parameter复制到多个GPU上，而复制后的parameter是Tensor类型的。 

希望这能帮到你。请问还有什么需要我帮忙的吗？

**Comment by ykaiqx** [comment]
谢谢你的反馈，请问这个是 web2显示的问题吗？不是服务器端端bug吧

**Comment by Do1e** [comment]
应该是web2的问题，后台显示发送的`info['answer'] = answer`就是上面的问题内容

**Comment by ykaiqx** [comment]
能告诉我，问的什么 问题 吗？

**Comment by Do1e** [comment]
比如：
* torch.parallel之后网络中的parameter变成了Tensor是为什么
* latex如何设置section的默认字体

好像只要答案包含`这样`的样式机会出错

**Comment by ykaiqx** [comment]
web 和 web3也有这样的错误吗？
这是我上面2个问题，请求后的截图
![7744D676-0D5D-4560-B5DC-B5170E438CB7](https://user-images.githubusercontent.com/56395004/226367965-eed19b22-b306-494f-be76-f90db6d7529a.png)
![BC012CD8-4948-44F4-8E04-58ACC765C175](https://user-images.githubusercontent.com/56395004/226368133-71e47529-0438-4959-bbc4-2ff8090b427d.png)

**Comment by Do1e** [comment]
web和web3没有对代码进行处理，所以没有这个问题。

那尝试一些别的问题呢，只要有`单行代码`样式就会出问题

**Comment by ykaiqx** [comment]
那就是web2的错误。web2示例不是我写的。联系下 @Hzzy2O

**Comment by Do1e** [comment]
那可以麻烦你设置一下Assignees吗

**Comment by duoduohe** [comment]
#23
