### ISSUE TITLE
关于 无法连接：no close frame received 相关问题的讨论

### ISSUE THREAD

**Issue by systemoutprintlnhelloworld** [XiaoXinYo/Bing-Chat#24]
如题，本地魔法环境一直无法获取到bing发送的数据，网页一直显示连接失败（持续两天，在本地和外网云主机报同样错误）

**Comment by ykaiqx** [comment]
我也遇到了问题，但我只是网页端（魔法了）无法使用，bing_chat可以用

**Comment by ykaiqx** [comment]
关闭魔法呢？

**Comment by systemoutprintlnhelloworld** [comment]
还是不行，但是用web.html时加载进去显示‘‘连接成功’’，但是点击对话框的‘‘请输入内容’’时显示连接断开，另外，如图所示https://imgse.com/i/ppBhP6P       ，报错显示无法找到cookie.json,但是我在同级目录下有该文件

**Comment by ykaiqx** [comment]
我指的网页端是https://www.bing.com/chat

**Comment by ykaiqx** [comment]
> 

cookie.json要与运行路径同级，建议在 bing_chat.py目录中启动终端

**Comment by systemoutprintlnhelloworld** [comment]
最新版本，同级目录使用终端打开后显示并未提示无法找到json文件，且web2.html进入后显示连接成功，但是一旦发送请求1s左右终端报错response["arguments"][0]["messages"][0][
KeyError: 'messages'，服务端显示连接终端

**Comment by ykaiqx** [comment]
我已经上传了新的版本，请将EdgeGPT库更新至（0.1.10.1），确保你的cookie没有过期

**Comment by K-h-Huang** [comment]
我的版本是0.1.20，开启后也是页面连接断开 最后几行报错是这样的
httpcore._exceptions.ConnectError: EOF occurred in violation of protocol (_ssl.c:1129)
INFO:     connection open
INFO:     connection closed
在网页上访问bing没问题，本地开了魔法的，要怎么解决呢？

**Comment by ykaiqx** [comment]
可以提供完整的报错截图吗

**Comment by K-h-Huang** [comment]
<img width="974" alt="1" src="https://user-images.githubusercontent.com/82552207/229412291-d89aca14-afbe-4492-bd9d-520d55d6054c.png">
<img width="1018" alt="2" src="https://user-images.githubusercontent.com/82552207/229412298-c2eaf961-0345-44ff-ab57-6b9ab56b28a9.png">
<img width="1074" alt="3" src="https://user-images.githubusercontent.com/82552207/229412304-76d49712-d3f0-44e8-a0bf-0b58e0fbf066.png">
<img width="1082" alt="4" src="https://user-images.githubusercontent.com/82552207/229412315-ecae9f47-6f5f-4cc0-b6c9-61b8d1e25558.png">
<img width="1070" alt="5" src="https://user-images.githubusercontent.com/82552207/229412324-5ee9e58b-49f1-41c0-bfd3-cca35b49bf31.png">

**Comment by ykaiqx** [comment]
如果不用ws连接，使用api还会报错吗？
`127.0.0.1:5000/api?question=你好&style=balanced`
你是用example的页面连接吗？

**Comment by K-h-Huang** [comment]
是的，使用exampl里的连接
不用ws连接是如何操作呢？
<img width="796" alt="7" src="https://user-images.githubusercontent.com/82552207/229413686-926ddf37-0203-477d-abbe-85fc0f953ac3.png">


我用浏览器直接输入了是这样子
<img width="455" alt="6" src="https://user-images.githubusercontent.com/82552207/229413483-3c5010d1-3372-4e8a-9f39-0a5d5f25a519.png">

**Comment by ykaiqx** [comment]
重新安装requirements.txt里面的库呢
