### ISSUE TITLE
all_proxy无效

### ISSUE THREAD

**Issue by redjumper** [XiaoXinYo/Bing-Chat#26]
和 #24 类似，报一样的错。尝试过all_proxy无效。现在[EdgeGPT](https://github.com/acheong08/EdgeGPT)支持proxy，直接使用edgegpt没有问题

**Comment by ykaiqx** [comment]
你EdgeGPT的proxy可以正常使用吗？
我这里不用梯子也能正常使用。

**Comment by redjumper** [comment]
不好意思，之前没说清楚，EdgeGPT也是设置了proxy才能正常使用

**Comment by ykaiqx** [comment]
<img width="218" alt="WeChatb9c43579278aa3df0ff5f4d923c532f8" src="https://user-images.githubusercontent.com/56395004/232691083-52e0e4dc-c1b1-4f2b-bcbe-80623bb3979f.png">
你是说这个proxy吧？

**Comment by redjumper** [comment]
是的
edgept启动是
```
python EdgeGPT.py --proxy http://ip.port --cookie-file COOKIE_FILE
或者
export all_proxy=http://ip.port
python EdgeGPT.py --cookie-file COOKIE_FILE
```

**Comment by ykaiqx** [comment]
好的，晚上我加下proxy，

**Comment by ykaiqx** [comment]
[已更新](https://github.com/XiaoXinYo/Bing-Chat/commit/c56e3febc67647adabbf2052e4d829a0761c296b)

**Comment by redjumper** [comment]
非常感谢，现在能用了
